database:
    driver: pdo_mysql
    host: localhost
    dbname: dorm
    user: homestead
    password: secret
    charset: utf8
    driverOptions:
        1002: "SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))"